### ISSUE TITLE
Token scope needs to expand , currently it is limited to domain of its issuer.

### ISSUE THREAD

**Issue by rajatkushawaha** [opencadc/ac#139]
When calling underlying apis from storage inventory the Authorization token is getting passed only when domain of the issuer of token is same as the calling api.
 the logic to setAuthorization header is present in cadc-util (ca.nrc.cadc.net.HttpTransfer)

      for (String domain : next.getDomains()) { 
          if (conn.getURL().getHost().endsWith(domain)) {
          ...............
          }} 
  
 Storage inventory can be deployed into different regions and the domain might be different for those regions , in this case Authorization token is not getting passed. This logic should be changed to accommodate all the domains.

**Comment by pdowler** [comment]
The current implementation of the IentityManager has to validate/augment an incoming auth token (AuthorizationTokenPrincipal) by calling the issuer and, if successful, it creates an AuthorizationToken and adds it to the credential set so that calls can be made on the user's behalf. Use case: subsequent call to a GMS service using IvoaGroupClient.

At the point of the validate(), the code only knows it's own trusted token issuer and this only knows that the operator of that software trusts that issuer (host) as a place to send user tokens, so that's the only domain it adds to the AuthorizationToken. Given that this is the "user service" and "groups" are tightly coupled with users, this is close to being the right choice for the user case.

For example, if the issuer was `https://srv.example.net/users` and the GMS service was `https://srv.example.net/groups` then the current code would enable a service that was configured with that issuer to successfully send the token to that gms service to check groups. A slightly different setup like issuer `https://issuer.example.net/` and `https://gms.example.net/` would not work as-is because of the different hostnames, but that's almost a bug... I say _almost_ because deriving a domain from a hostname and then assuming tokens are valid for the whole domain is a huge assumption that won't always be true and will sometimes be really dangerous!

I haven't seen or understood something in OIDC docs that says how code can figure out where it is safe to send tokens (eg in the context of the `StandardIdentityManager.validate()` method). I feel like the issuer should be the one to declare or advertise where tokens can be safely sent (which internet hosts/domains are part of it's "administrative domain")... lots TBD here.

**Comment by brianmajor** [comment]
Would just like to flag this issue as increasingly important as the UK deployment of GMS (on a different host as IAM, but some domain) is being deployed.

**Comment by pdowler** [comment]
PR #143 improves this (minimally) so that AuthorizationToken includes the hostname of the OICD issuer *and* the hostname of a trusted GMS service (configured as usual via cadc-registry config). Since the  LocalAuthority API only allows for one {standardID} = {resourceID} mapping, this enables a single GMS service that is rpesumably co-located with the OIDC issuer.
